<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Macfadyen\CustomerCustomAttributes\Block\Widget\AddressType $block */
?>
<div class="field gender">
    <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('address_type')) ?>"><span><?= $block->escapeHtml(__('Address Type')) ?></span></label>
    <div class="control">
        <select id="<?= $block->escapeHtmlAttr($block->getFieldId('address_type')) ?>" name="<?= $block->escapeHtmlAttr($block->getFieldName('address_type')) ?>" title="<?= $block->escapeHtmlAttr(__('Address Type')) ?>">
            <?php $options = $block->getAddressTypeOptions(); ?>
            <?php $value = $block->getAddressType();?>
            <?php foreach ($options as $option):?>
                <option value="<?= $block->escapeHtmlAttr($option->getValue()) ?>"<?php if ($option->getValue() == $value) echo ' selected="selected"' ?>><?= $block->escapeHtml(__($option->getLabel())) ?></option>
            <?php endforeach;?>
        </select>
    </div>
</div>
